services:
  trading-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
      - TRUTHSOCIAL_USERNAME=${TRUTHSOCIAL_USERNAME} #For TruthBrush
      - TRUTHSOCIAL_PASSWORD=${TRUTHSOCIAL_PASSWORD} #For TruthBrush
      - GROQ_API_KEY=${GROQ_API_KEY}
      - DOCKER_CONTAINER=true
    ports:
      - "9222:9222"  # For Chrome remote debugging if needed
    restart: unless-stopped